export const CURRENT_PAGE = 'CURRENT_PAGE';
export const GET_BIKES = 'GET_BIKES'; 
export const GET_BIKES_DETAIL = "GET_BIKES_DETAIL"
export const TYPE_FILTER = 'TYPE_FILTER';
export const TRACTION_FILTER = 'TRACTION_FILTER';

