export const CURRENT_PAGE = 'CURRENT_PAGE';
export const SET_PARAMETERS = 'SET_PARAMETERS';
export const GET_BIKES = 'GET_BIKES';
export const GET_RENDERED_BIKES = 'GET_RENDERED_BIKES';
export const GET_BIKES_DETAIL = 'GET_BIKES_DETAIL';
export const GET_USER = 'GET_USER';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_BOOKING = 'ADD_BOOKING';
export const POST_BOOKINGS = 'POST_BOOKINGS';
export const GET_FAMOUS_BIKES = 'GET_FAMOUS_BIKES';
export const GET_ACCESORIES = "GET_ACCESORIES";
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const GET_ALL_BOOKINGS = 'GET_ALL_BOOKINGS';
export const POST_EXPERIENCE = 'POST_EXPERIENCE'
export const GET_ALL_EXPERIENCES = "GET_ALL_EXPERIENCES"
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SET_BIKES_DETAIL = 'SET_BIKES_DETAIL';
export const GET_DISABLED_DATES = 'GET_DISABLED_DATES';
export const GET_USER_BOOKINGS = 'GET_USER_BOOKINGS';
export const GET_ALL_FAVORITES = 'GET_ALL_FAVORITES'


